export enum AppState {
  RESTAGE_TRIGGERED = 'RESTAGE_TRIGGERED',
  RESTAGING = 'RESTAGING',

  STOP_TRIGGERED = 'STOP_TRIGGERED',
  STOPPING = 'STOPPING',

  START_TRIGGERED = 'START_TRIGGERED',
  STARTING = 'STARTING',
}
